apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: flask-dockerfile-example-i1nd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flask-dockerfile-example-i1nd
    app.kubernetes.io/part-of: my-app
  name: flask-dockerfile-example-i1nd
  namespace: rorai-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: flask-dockerfile-example-i1nd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: flask-dockerfile-example-i1nd
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:rrPIt-flask-dockerfile-example-i1nd
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 5000
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 5000
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
